### ISSUE TITLE
Instructions needed for time synchronization with a NTP server as egcurl is time sensitive

### ISSUE THREAD

**Issue by tonytan4ever** [akamai-open/edgegrid-curl#7]
Often when we use egcurl we will get this result:
  {
  "type": "https://problems.luna.akamaiapis.net/-/pep-authn/request-error",
  "title": "Bad request",
  "status": 400,
  "detail": "Invalid timestamp",
  "instance": "https://akab-3r276kizolbgfqbi-6tnfu4jessqtn4b4.luna.akamaiapis.net/partner-api/v1/network/production/properties/208892/sub-properties/test.mocksite4.com/policypartner-api/v1/network/production/properties/None/sub-properties/test.mocksite4.com/policy",
  "method": "PUT",
  "serverIp": "<A server ip>",
  "clientIp": "<A client ip>",
  "requestId": "<a request id>",
  "requestTime": "<a time stamp>"
}

This is because OPEN API are time sensitive. I was wondering if an instruction on how to tune up your system time with a NTP server could be written, (for eg: on Windows, Linux/Ubuntu, and Mac OSX etc), so the users will know what to do when they run into this issue.

**Comment by maglietti** [comment]
Hi tonwtan4ever,

Yes, the Akamai Open APIs are time sensitive. We recommend that you sync your API client host to a Stratum 2 or better time source via [NTP](http://en.wikipedia.org/wiki/Network_Time_Protocol). 

Please take a look at our recommendations and instructions here: [Troubleshooting: "Invalid Timestamp" error](https://community.akamai.com/docs/DOC-1336)

Thanks. 

-- Michael
